language: java
jdk: 
  - oraclejdk12
before_install:
  # Update Travis CI java (default = 8)
  - sudo apt-get update
  - cd AerariumBackend/
  - echo "Aerarium - Compilation/build started..."
  - ./gradlew clean
  - cd ..
  - echo "Aerarium - Everything good!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag aerarium_backend:latest nickchecan/aerarium:latest;
    docker push nickchecan/aerarium:latest;
  on:
    branch: master
after_success:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel # Force latest wheel version installation
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  - docker tag nickchecan/aerarium:latest $IMAGE_REPO_URL:latest
  - docker push $IMAGE_REPO_URL:latest
notifications:
  # Check integration with Slack or Rocket
  email: false